name: Cross-platform Builds Autocomplete
permissions:
  contents: read
  
on:
  pull_request:
    paths-ignore: 
      - 'libvlmath/**'
      - 'toolchains/**'
      - 'CMake**.**'
    
jobs:
  build:
    uses: VolcanusLucis/.github/.github/workflows/build-cmake-project-presets.yml@master
    with:
      architecture: ''
      build-tool: ''
      build-type: ''
      compiler: ''
      target: ''
      bypass: true
      
  build-all:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo "No builds needed!"